In [1]:
import torch

X = torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]])

X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [ ]:
# shape

X.shape

torch.Size([2, 3])

In [ ]:
# data type
X.dtype

torch.float32

In [4]:
# indexing
X[0, 1]

tensor(4.)

In [5]:
X[:, 1]

tensor([4., 3.])

In [6]:
# math

10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [ ]:
X.exp()

tensor([[   2.7183,   54.5982, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [8]:
X.mean()

tensor(3.8333)

In [9]:
X.max(dim=0)  # max values along dimension 0 (i.e., max value per column)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [10]:
X @ X.T  # matrix transpose and matrix multiplication

tensor([[66., 56.],
        [56., 49.]])

In [11]:
import numpy as np
X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [ ]:
torch.tensor(np.array([[1., 4., 7.], [2., 3., 6.]]))

# note that you should always stick to dtype=float32

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [15]:
torch.FloatTensor(np.array([[1., 4., 7.], [2., 3., 6]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [17]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [18]:
X.relu_()
X

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [ ]:
# Hardware acceleration

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

device

'mps'

In [21]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
M = M.to(device)

In [22]:
M.device

device(type='mps', index=0)

In [23]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device)

In [24]:
R = M @ M.T  # run some operations on the GPU
R

tensor([[14., 32.],
        [32., 77.]], device='mps:0')

In [25]:
M = torch.rand((1000, 1000))  # on the CPU
%timeit M @ M.T

585 μs ± 532 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [26]:
M = torch.rand((1000, 1000), device=device)
%timeit M @ M.T

377 μs ± 1.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
